"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['vinyl_scrobbler.py']
DATA_FILES = ['about_config.json']
OPTIONS = {
    'argv_emulation': False,
    'iconfile': 'icon.icns',
    'plist': {
        'LSUIElement': True,
        'CFBundleName': 'Vinyl Scrobbler',
        'CFBundleDisplayName': 'Vinyl Scrobbler',
        'CFBundleGetInfoString': 'Vinyl Scrobbler',
        'CFBundleIdentifier': 'com.russ.vinylscrobbler',
        'CFBundleVersion': '0.1.0',
        'CFBundleShortVersionString': '0.1.0',
        'NSHumanReadableCopyright': ' 2024 Russ McKendrick'
    },
    'packages': [
        'pylast',
        'discogs_client',
        'objc',
        'Foundation',
        'AppKit',
        'UserNotifications',
        'requests',
        'httpx',
        'httpcore',
        'certifi',
        'idna',
        'anyio',
        'sniffio',
        'h11',
        'charset_normalizer'
    ],
    'includes': [
        'pkg_resources',
        'decimal',
        'numbers',
        'json',
        'logging',
        'getpass',
        'threading',
        'time',
        'datetime'
    ]
}

setup(
    app=APP,
    name='Vinyl Scrobbler',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=[
        'pyobjc-core',
        'pyobjc-framework-Cocoa',
        'pyobjc-framework-UserNotifications',
        'pylast',
        'discogs-client',
        'requests',
        'charset_normalizer'
    ]
)